
 spring.datasource.url=${BD_PROD_URL}
 spring.datasource.username={$BD_PROD_USERNAME}
 spring.datasource.password={$BD_PRDO_PASSWORD}
 spring.datasource.driver-class-name=org.postgresql.Driver

 spring.jpa.database-platform=org.hibernate.dialect.postgresql
 spring.jpa.hibernate.ddl-auto=validate
 spring.jpa.show-sql=false

spring.flyway.baseline-on-migrate=false
springdoc.swagger-ui.enabled=false